[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen-console-logger = "0.1.1"
gloo = "0.11.0"
log = "0.4.20"
web-sys = "0.3.68"
wext = "0.7.2"
